#!/bin/bash
# Q-Chem trans-azobenzene vertical excitations in gas

#SBATCH --job-name=trans_vert_gas
#SBATCH --output=trans_vert_gas.o%j
#SBATCH --error=trans_vert_gas.e%j

#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=8000MB
#SBATCH --time=04:00:00
#SBATCH --account=krylov_547      

module purge
module load usc
module load qchem/6.3.0-openmp

cd $SLURM_SUBMIT_DIR
hostname

qchem -nt 8 trans_vert_gas.in trans_vert_gas.qcout

